apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: raelmartins44/gitopsfc
  newTag: 3e90ba581be039ebffa80bbd4508cc45464dbcb0
- name: goserver-gitops
  newName: raelmartins44/gitopsfc
  newTag: 3e90ba581be039ebffa80bbd4508cc45464dbcb0
