apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: raelmartins44/gitopsfc
  newTag: 4d9dd9ec4b5ce61815a26fc125ae3c2b1438610e
- name: goserver-gitops
  newName: raelmartins44/gitopsfc
  newTag: c6c4777817f38039cb063e2ff786a5292f8aba24
